FROM node:8

#RUN apt-get update
#RUN apt-get install -y git

RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

COPY . /home/node/app
RUN chown -R node /home/node/app

#RUN npm install -g gulp

RUN usermod -u 106 node

USER node
WORKDIR /home/node/app
ENTRYPOINT ["/home/node/app/resources/build.sh"]